version: "3.8"

services:
  # 客户端 - Flutter Web 应用
  client:
    build:
      context: ..
      dockerfile: manifests/docker/Dockerfile.client
    ports:
      - "8080:8080"
    restart: unless-stopped

  # 服务端 - FastAPI
  server:
    build:
      context: ..
      dockerfile: manifests/docker/Dockerfile.server
    ports:
      - "9000:9000"
    environment:
      - ALIBABA_CLOUD_ACCESS_KEY_ID=${ALIBABA_CLOUD_ACCESS_KEY_ID}
      - ALIBABA_CLOUD_ACCESS_KEY_SECRET=${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
      - OSS_BUCKET=${OSS_BUCKET}
    restart: unless-stopped
