window.graphData = {
  "graphNodes": [
    { "id": "dir-root", "label": "元仓库", "group": "Dir", "parent": null },
    { "id": "dir-roadmap", "label": "roadmap", "group": "Dir", "parent": "dir-root" },
    { "id": "dir-plat", "label": "平台", "group": "Dir", "parent": "dir-root" },
    { "id": "dir-plat-docs", "label": "docs", "group": "Dir", "parent": "dir-plat" },
    { "id": "dir-plat-drd", "label": "drd", "group": "Dir", "parent": "dir-plat-docs" },
    { "id": "dir-plat-qa", "label": "qa", "group": "Dir", "parent": "dir-plat-docs" },
    { "id": "dir-plat-src", "label": "src", "group": "Dir", "parent": "dir-plat" },
    { "id": "dir-plat-test", "label": "test", "group": "Dir", "parent": "dir-plat" },
    { "id": "dir-plat-config", "label": "config", "group": "Dir", "parent": "dir-plat" },
    { "id": "dir-ex", "label": "示例", "group": "Dir", "parent": "dir-root" },
    { "id": "dir-lib", "label": "库", "group": "Dir", "parent": "dir-root" },
    { "id": "agent-meta", "label": "meta-agent", "group": "Agent", "parent": "dir-root" },
    { "id": "agent-plat", "label": "platform-agent", "group": "Agent", "parent": "dir-plat" },
    { "id": "agent-ex", "label": "example-agent", "group": "Agent", "parent": "dir-ex" },
    { "id": "agent-lib", "label": "lib-agent", "group": "Agent", "parent": "dir-lib" },
    { "id": "agent-drd", "label": "drd-agent", "group": "Agent", "parent": "dir-plat-drd" },
    { "id": "agent-qa", "label": "qa-agent", "group": "Agent", "parent": "dir-plat-qa" },
    { "id": "agent-code", "label": "code-agent", "group": "Agent", "parent": "dir-plat-src" },
    { "id": "agent-test", "label": "test-agent", "group": "Agent", "parent": "dir-plat-test" },
    { "id": "agent-config", "label": "config-agent", "group": "Agent", "parent": "dir-plat-config" },
    { "id": "file-roadmap", "label": "未命名.md", "group": "File", "parent": "dir-roadmap" },
    { "id": "file-plan", "label": "PLAN.md", "group": "File", "parent": "dir-plat" },
    { "id": "file-status", "label": "STATUS.md", "group": "File", "parent": "dir-plat" },
    { "id": "file-drd", "label": "支付设计.md", "group": "File", "parent": "dir-plat-drd" },
    { "id": "file-qa", "label": "测试策略.md", "group": "File", "parent": "dir-plat-qa" },
    { "id": "file-code", "label": "payment.ts", "group": "File", "parent": "dir-plat-src" }
  ],
  "graphEdges": [
    { "id": "w1", "from": "agent-meta", "to": "file-roadmap", "type": "write", "label": "修改", "events": [] },
    { "id": "w2", "from": "agent-meta", "to": "file-plan", "type": "write", "label": "写入", "events": [] },
    { "id": "w3", "from": "agent-plat", "to": "file-status", "type": "write", "label": "回报", "events": [] },
    { "id": "w4", "from": "agent-drd", "to": "file-drd", "type": "write", "label": "修改", "events": [] },
    { "id": "w5", "from": "agent-qa", "to": "file-qa", "type": "write", "label": "生成", "events": [] },
    { "id": "w6", "from": "agent-code", "to": "file-code", "type": "write", "label": "实现", "events": [] },
    { "id": "t1", "from": "agent-meta", "to": "agent-plat", "type": "trigger", "label": "更新PLAN", "events": [{ "time": "14:18:30", "payload": { "version": "v2" } }] },
    { "id": "t2", "from": "agent-plat", "to": "agent-drd", "type": "trigger", "label": "设计任务", "events": [] },
    { "id": "t3", "from": "agent-drd", "to": "agent-qa", "type": "trigger", "label": "drd.finalized", "events": [{ "time": "14:30:05", "payload": { "status": "final" } }] },
    { "id": "t4", "from": "agent-drd", "to": "agent-code", "type": "trigger", "label": "design.finalized", "events": [{ "time": "14:30:05", "payload": { "status": "final" } }] },
    { "id": "t5", "from": "agent-code", "to": "agent-test", "type": "trigger", "label": "code.implemented", "events": [{ "time": "14:25:00", "payload": { "status": "implemented" } }] },
    { "id": "f1", "from": "agent-test", "to": "agent-code", "type": "feedback", "label": "bug.report", "events": [{ "time": "14:20:45", "payload": { "bug": "回调未处理超时" } }] },
    { "id": "f2", "from": "agent-qa", "to": "agent-drd", "type": "feedback", "label": "change.request", "events": [{ "time": "14:28:12", "payload": { "issue": "缺少超时处理", "suggestion": "增加 timeout 参数" } }] }
  ]
};
